### ISSUE TITLE
Don't override Netlify's default caching settings

### ISSUE THREAD

**Issue by dennis47528** [bazzite/nuxt-netlify#3]
**Describe the bug**
Netlify already uses custom caching headers that you should not override, bad practice.
(please see 'Additional context' below for more information)

> Netlify sets the caching very intentionally to max-age of 0 but it does allow content to be cached AND enables atomic rollbacks and deploys.

**Expected behavior**
Remove the Cache-Control header for the _nuxt folder.
Perhaps you can remove the Cache-Control header for the sw.js file too, i'm not sure about that.

https://github.com/bazzite/nuxt-netlify/blob/2a6a6aa53484715f6f3449492efc07626e0bd046/lib/constants.js#L36-L37

⚠👇
**Additional context**
- https://www.netlify.com/blog/2017/02/23/better-living-through-caching/
- https://stackoverflow.com/a/52323443

**Comment by juliomrqz** [comment]
Hi, @dennis47528. There is nothing wrong setting the cache-control header for the `/_nuxt` folder, this is considered safe because all assets should be correctly hashed there. 

The links you provided conclude that the cache-control header value of the non-immutable (unhashed) assets should be managed by Netlify, and our plugin respects that.

Regarding the `sw.js` file, it should not be cached under any circumstances, and that's the reason we use `Cache-Control: no-cache`.

If you do not want to use the default caching values, you can deactivate them using this option https://www.bazzite.com/docs/nuxt-netlify/configuration/#mergecachingheaders.

Additional Context:
- https://www.netlify.com/blog/2018/09/21/international-service-worker-caching-awareness-day/
